### PR TITLE
WIP Add oversubscribe

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds ` -oversubscribe` to the MPI tests allowing the tests to run on dual-core processors.

Reviewers: Is this option supported by all major MPI implementations? If yes, please merge.

### CODE REVIEW

**Comment by MakisH** [comment]
Works on OpenMPI 1.10.2 with 2*2 cores (so, no oversubscription). I will also test on a VM.

**Comment by floli** [comment]
It's not there with MPICH 3.3.1:
```
lindnefn@asaru ~ % /opt/mpich/bin/mpirun -oversubscribe -n 6 ls
[mpiexec@asaru] match_arg (../../../../src/pm/hydra/utils/args/args.c:163): unrecognized argument oversubscribe
[mpiexec@asaru] HYDU_parse_array (../../../../src/pm/hydra/utils/args/args.c:178): argument matching returned error
[mpiexec@asaru] parse_args (../../../../src/pm/hydra/ui/mpich/utils.c:1642): error parsing input array
[mpiexec@asaru] HYD_uii_mpx_get_parameters (../../../../src/pm/hydra/ui/mpich/utils.c:1694): unable to parse user arguments
[mpiexec@asaru] main (../../../../src/pm/hydra/ui/mpich/mpiexec.c:148): error parsing parameters
```

**Comment by fsimonis** [comment]
So this is an OpenMPI 2+ problem and we just have to tell the user about this.
