### ISSUE TITLE
Failing PetRBF unit test

### ISSUE THREAD

**Issue by uekerman** [precice/precice#249]
The following test currently fails on my laptop:

```
/home/uekerman/Repos/precice/src/mapping/tests/PetRadialBasisFctMappingTest.cpp(1326): error: in "MappingTests/PetRadialBasisFunctionMapping/Serial/ConsistentPolynomialSwitch": check outData->values()[0] == 1.0 has failed [-nan != 1]. Relative difference exceeds tolerance [-nan > 1e-06]
```

Ubuntu 18.04, PETSc 3.7, develop branch. Has previously worked I guess.

**Comment by MakisH** [comment]
For the coding days: try this for different systems and document here.

**Comment by fsimonis** [comment]
This works with PETSc 3.10

**Comment by ajaust** [comment]
I saw this error yesterday when compiling with CMake. When running the tests through the python script  `tools/compileAndTest.py`, I got the same error message. When running the test using `testprecice` directly I got different errors. This might (however) linked to the CMake build system. 


I will post my bash script for installation of preCICE here. It will checkout the current version from GitHub and build it with CMake, run the tests and afterwards install it. You can also adapt it so it downloads a release `tar.gz`.

```bash
#/bin/bash -l

target_dir="precice-git-cmake"
nworkers=8
ntestworkers=4

run_dir=${PWD}
install_dir=${run_dir}/${target_dir}/precice-install

if [[ ! -f ${precice_targz} ]]; then
#  wget https://github.com/precice/precice/archive/${precice_targz}
  git clone git@github.com:precice/precice.git ${target_dir}
fi

#if [ ! -d "${target_dir}" ]; then
#  mkdir -p ${target_dir}
#  tar xzf ${precice_targz} -C ${target_dir}
#  cd ${target_dir} 
#  precice_dir="precice-${precice_ver}"
#  cmd="mv ${precice_dir}/* ."
#  echo ${cmd}
#  ${cmd}
#  rm -rf ${precice_dir}
#  cd ..
#fi
cd ${target_dir}

export PRECICE_ROOT=${PWD}

module purge

rm -rf build 2> /dev/null

build_dir="${PWD}/precice-build"

mkdir -p ${build_dir}
cd ${build_dir}

build_path=${PWD}

echo ${PWD}
cmake -DCMAKE_BUILD_TYPE=Debug \
  -DBUILD_SHARED_LIBS=ON \
  -DMPI=ON \
  -DPETSC=ON \
  -DPYTHON=ON \
  -DCMAKE_INSTALL_PREFIX=${install_dir} \
  ${PRECICE_ROOT}

make -j ${nworkers}

# Run tests
mkdir -p $PRECICE_ROOT/build && ln -s ${PWD} $PRECICE_ROOT/build/last
cd ${PRECICE_ROOT}
python3 tools/compileAndTest.py -t --run_test="\!@MPI_Ports" --run_test="\!MappingTests/PetRadialBasisFunctionMapping/Parallel/*"

echo "TEST AGAIN"
echo ""

cd ${build_path}
mpirun -np 4 ./testprecice --run_test="\!@MPI_Ports" --run_test="\!MappingTests/PetRadialBasisFunctionMapping/Parallel/*"

cd ${build_path}
make install
```

**Comment by ajaust** [comment]
If you want to build with SCons you could try the following script:

```bash
#/bin/bash -l

precice_ver="git"
nworkers=8
target_dir="precice-git"


if [[ ! -d ${target_dir} ]]; then
  git clone git@github.com:precice/precice.git ${target_dir}
fi

cd ${target_dir}
export PRECICE_ROOT=${PWD}

scons petsc=yes python=yes -j ${nworkers}

./tools/compileAndTest.py -t
```

**Comment by uekerman** [comment]
The test also fails on SuperMUC, built with cmake and PETSc version 3.8
